export const backendSkills = {
   'Установленные пакеты': [
      'devDependencies:',
      '- @nestjs/cli',
      '- @nestjs/schematics',
      '- @types/axios',
      '- @types/cookie-parser',
      '- @types/cors',
      '- @types/express',
      '- @types/express-session',
      '- @types/node',
      '- @types/passport',
      '- @types/passport-jwt',
      '- @types/uuid',
      '- @typescript-eslint/eslint-plugin',
      '- @typescript-eslint/parser',
      '- eslint',
      '- eslint-config-prettier',
      '- eslint-plugin-prettier',
      '- prettier',
      '- source-map-support',
      '- ts-loader',
      '- ts-node',
      '- tsconfig-paths',
      '- typescript',
      '',
      'dependencies:',
      '- @nestjs/cache-manager',
      '- @nestjs/common',
      '- @nestjs/config',
      '- @nestjs/core',
      '- @nestjs/jwt',
      '- @nestjs/mongoose',
      '- @nestjs/passport',
      '- @nestjs/serve-static',
      '- @nestjs/typeorm',
      '- axios',
      '- body-parser',
      '- cache-manager',
      '- class-validator',
      '- connect-mongo',
      '- cookie-parser',
      '- crypto',
      '- csrf-csrf',
      '- dotenv',
      '- express-session',
      '- firebase-admin',
      '- mongoose',
      '- nestjs-cls',
      '- nestjs-paginate',
      '- passport',
      '- passport-jwt',
      '- typeorm',
      '- uuid',
   ],
   NestJS: [
      'Код можно посмотреть здесь -> https://github.com/Vik163/shop-pizza-pet-project_api',
      'Хоть и склоняюсь больше к фронтенду, но бекенд тоже нравиться.',
      'На курсах, в небольшом объеме, давали express.js, что для простого приложения достаточно, но после пришлось учиться самому. Выбрал NestJS, чтобы практиковаться в Typescript, так как считаю его необходимым для разработки',
   ],
   MongoDB: undefined,
   TypeOrm: ['Поверхностные знания. Использовал для пагинации'],
   Cookie: undefined,
   Sessions: undefined,
   Cache: undefined,
   CSRF: undefined,
   Авторизация: [
      '- Firebase - по номеру телефона',
      '- Яндекс ID',
      'При входе создаются два токена: access и refresh, создается сессия. Refresh кодируется и с сессией сохраняются в БД.',
   ],
};
