export const frontendSkills = {
   'Установленные пакеты': [
      'devDependencies:',
      '- @babel/core',
      '- @babel/plugin-transform-runtime',
      '- @babel/plugin-transform-typescript',
      '- @babel/preset-env',
      '- @babel/preset-react',
      '- @babel/preset-typescript',
      '- @pmmmwh/react-refresh-webpack-plugin',
      '- @svgr/webpack',
      '- @types/circular-dependency-plugin',
      '- @types/grecaptcha',
      '- @types/jwt-decode',
      '- @types/node',
      '- @types/react',
      '- @types/react-dom',
      '- @types/react-router-dom',
      '- @types/webpack',
      '- @types/webpack-bundle-analyzer',
      '- @types/webpack-dev-server',
      '- @typescript-eslint/eslint-plugin',
      '- @typescript-eslint/parser',
      '- @vitejs/plugin-react',
      '- @yandex/ymaps3-types',
      '- babel-loader',
      '- circular-dependency-plugin',
      '- concurrently',
      '- css-loader',
      '- eslint',
      '- eslint-config-airbnb',
      '- eslint-config-prettier',
      '- eslint-config-standard-with-typescript',
      '- eslint-plugin-import',
      '- eslint-plugin-n',
      '- eslint-plugin-prettier',
      '- eslint-plugin-promise',
      '- eslint-plugin-react',
      '- eslint-plugin-react-hooks',
      '- eslint-plugin-ulbi-eslint-plugin',
      '- eslint-plugin-ulbi-tv-plugin',
      '- eslint-plugin-unused-imports',
      '- file-loader',
      '- fork-ts-checker-webpack-plugin',
      '- html-webpack-plugin',
      '- mini-css-extract-plugin',
      '- prettier',
      '- react-refresh',
      '- sass',
      '- sass-loader',
      '- style-loader',
      '- ts-loader',
      '- ts-morph',
      '- ts-node',
      '- tsconfig-paths-webpack-plugin',
      '- typescript',
      '- vite',
      '- vite-plugin-svgr',
      '- webpack',
      '- webpack-bundle-analyzer',
      '- webpack-cli',
      '- webpack-dev-server',
      '',
      'dependencies:',
      '- @pbe/react-yandex-maps',
      '- @react-spring/web',
      '- @reduxjs/toolkit',
      '- @use-gesture/react',
      '- dayjs',
      '- dotenv',
      '- firebase',
      '- jwt-decode',
      '- react',
      '- react-dadata',
      '- react-dom',
      '- react-redux',
      '- react-router-dom',
      '- react-visibility-sensor',
      '- uid',
   ],
   React: [
      'Код можно посмотреть здесь -> https://github.com/Vik163/shop-pizza-pet-project',
      'Клиентская часть приложения написана на React - 18,',
      '- Роутинг - react-router-dom - 6;',
      'Использовал следующие инструменты:',
      ' - Lazy - динамическая подгрузка компонентов,',
      ' - Цветовые темы,',
      ' - Пагинация - на выбор два типа загрузки товара: выбор страниц или бесконечный скролл,',
      ' - Сохранение скролла (useTrottle),',
      ' - Горизонтальная прокрутка карточек. Использовал ленивую подгрузку библиотек (@react-spring/web, @use-gesture/react),',
   ],
   Webpack: undefined,
   'Redux Toolkit': [
      ' - Ассинхронные редьюсеры',
      ' - AsyncThunk',
      ' - EntityAdapter',
      ' - RTK Query - все запросы',
   ],
   'Feature-Sliced Design': undefined,
   Eslint: undefined,
   Авторизация: ['- По номеру телефона - Firebase,', '- Яндекс ID'],
   CSRF: [
      '- При регистрации или аутентификации получаю новый токен с сервера и сохраняю его в стейт',
      '- При отправке формы, в перехватчике запросов, получаю токен из стейта и добавляю его в заголовок запроса',
   ],
};
